name: Run Python Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 */5 * * *'  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: purge cache
      run: pip cache purge

    - name: Time Installation
      run: pip install pytz

    - name: site
      run: python -m site --user-site

    - name: update
      run: pip install --upgrade pip
           
    - name: Install dependencies
      run: pip install -r requirements.txt
           
    - name: Run bot
      run: python3 bot.py & python3 status_manager.py
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
